version: "3.2"
services:
  data-producer:
    container_name: data-producer
    build:
      dockerfile: crypto-data/Dockerfile
    volumes:
      - ./:/usr/src
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - crypto-network

  news-producer:
    container_name: news-producer
    build:
      dockerfile: crypto-news/Dockerfile
    volumes:
      - ./:/usr/src
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - crypto-network

  streamlit:
    container_name: streamlit
    build:
      context: ./streamlit
    volumes:
      - ./streamlit:/usr/src
    depends_on:
      - data-producer
      - news-producer
    networks:
      - crypto-network
    ports:
      - 8501:8501

  mongodb:
    image: mongo
    container_name: mongodb
    hostname: mongodb
    restart: unless-stopped
    command: mongod --auth
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: big-data-project
      MONGODB_DATA_DIR: /data/db
      MONGODB_LOG_DIR: /dev/null
    volumes:
      - ./streamlit/data/db:/data/db
    networks:
      - crypto-network

  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - crypto-network

  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_CREATE_TOPICS: crypto_raw,crypto_news
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100
    healthcheck:
      test: ["CMD", "bash", "-c", "unset", "JMX_PORT", ";", "/bin/kafka-topics.sh", "--zookeeper", "zookeeper:2181", "--list"]
      interval: 20s
      timeout: 10s
      retries: 3
    networks:
      - crypto-network
    ports:
      - 9092:9092
      - 30001:30001

networks:
  crypto-network:
    driver: "bridge"
